### ISSUE TITLE
Admin to selectively upload pictures for plants 

### ISSUE THREAD

**Issue by ferri082** [UMM-CSci-3601-S17/digital-display-garden-iteration-4-dorfner-v2#7]

**Comment by ferri082** [comment]
- [ ] store photos 
- [ ] replacing photos 
- [ ] adding photos to plant pages 
- [ ] delete at the end of year

**Comment by lverns** [comment]
Moving this back into In Progress, since there are no PRs to review at the moment.

**Comment by ferri082** [comment]
things to do 
- [ ] refresh photo automatically on admin side
- [ ] testing 
- [ ] fix visit timestamps
- [ ] fix browse to not store photo

**Comment by lverns** [comment]
Do I have to manually create the `.photos` folder? I merged `master` into `OAuth` and I'm getting this exception (in the server log) when trying to upload a picture. However, the I get "Your file was successfully uploaded for plant 16305." on the website.

```
java.nio.file.NoSuchFileException: .photos/2017-04-24 16:03:49
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at umm3601.digitalDisplayGarden.Photos.saveImage(Photos.java:38)
	at umm3601.Server.lambda$main$19(Server.java:298)
	at spark.RouteImpl$1.handle(RouteImpl.java:61)
	at spark.http.matching.Routes.execute(Routes.java:61)
```

**Comment by ferri082** [comment]
I have an idea why it does that. It may be breaking after we tried setting liveupload directories under photos. Didn't notice it since .Photos was already set up.
